---
title: "Homework 1: Map making practice"
author: "Jaslyn Miura"
format: html
---


```{r}
library(tidyverse)
library(sf)
library(here)
library(tmap)

# read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb")) 

# filter to a state you are interested in
washington <- ejscreen %>%
  dplyr::filter(ST_ABBREV == "WA") 

# filter to a county you are interested in
seattle <- washington %>%
  dplyr::filter(CNTY_NAME %in% c("King County"))

# find the average values for all variables within counties
wa_counties <- aggregate(washington, by = list(washington$CNTY_NAME), FUN = mean)


```


```{r}

tm_shape(wa_counties) +
  tm_polygons(
    fill = "LOWINCPCT",
    fill.scale = tm_scale(values = "YlGn"),
    fill.legend = tm_legend(title = "Low Income")) +
  tm_title(text = "Washington State Low Income Percentages by County") +
  tm_scale_bar() +
  tm_compass(position = c("left", "bottom"))


```

```{r}

tm_shape(wa_counties) +
  tm_polygons(
    fill = "D2_UST",
    fill.scale = tm_scale(values = "YlGn"),
    fill.legend = tm_legend(title = "Number of USTs")) +
  tm_title(text = "Average number of LUSTs leaking underground storage tanks")

```

```{r}

```

